package com.sunbeam;

public enum EMenu {
	EXIT,
	INSERT_CANDIDATE,
	DISPLAY_ALL,
	INCREAMENT_VOTERS_OF_CANDIDATE,
	DELETE_CANDIDATE,
	FIND_CANDIDATE_BY_ID,
	FIND_CANDIDATE_BY_PARTY,
	DISPLAY_TOTAL_VOTES_OF_PARTY
}
