package com.sunbeam;

import java.sql.PreparedStatement;

public enum EMenu {

	EXIT,
	INSERT_CANDIDATE,
	UPDATE_CANDIDATE,
	DELETE_CANDIDATE,
	FIND_CANDIDATE_BY_ID,
	FIND_CANDIDATE_BY_PARTY,
	DISPLAY_ALL_CANDIDATE,
	DISPLAY_PARTYWISE_VOTE
	
}
